name: Test templates

on: [push, pull_request]

jobs:
  test_templates:
    runs-on: ubuntu-latest
    container: ghcr.io/quattor/quattor-test-container:latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: test templates
      run: ./test_templates.sh
